### ISSUE TITLE
ImportError: cannot import name 'pcbdraw' from 'pcbdraw'

### ISSUE THREAD

**Issue by dhaillant** [yaqwsx/PcbDraw-Lib#28]
Hello (again),

I'm trying to execute scripts/create_template.py

```
$ scripts/create_template.py 
Traceback (most recent call last):
  File "scripts/create_template.py", line 3, in <module>
    from pcbdraw import pcbdraw
ImportError: cannot import name 'pcbdraw' from 'pcbdraw' (/home/david/.local/lib/python3.8/site-packages/pcbdraw/__init__.py)

```
I'm probably not using it as I should. Could you please give me a hint on how to use it? Thank you!

```
$ pcbdraw --version
pcbdraw, version 0.9.0+44.g481dcdd

```
and PcbDraw-Lib is probably up-to-date too:
```
$ git log -1
commit d582bc725fe987e35f291bc06e318cf6d3b263d2 (HEAD -> master, origin/master, origin/HEAD)
Author: Electro707 <general@electro707.com>
Date:   Sat Mar 26 01:52:13 2022 -0400
```

**Comment by guigur** [comment]
same problem for me

**Comment by MatteoTondelli** [comment]
I also ran into this problem with PcbDraw version `1.0.1` while trying to execute the `create_template.py` script.

For me the solution was to install PcbDraw version `0.9.0` from pip.

**Comment by Electro707** [comment]
Yeah it seems that after the 1.x.x API and internal changes with PCBDraw the `create_template.py` script is broken.

Unfortunately I don't see an easy way of updating the script without a lot of extra effort.

**Comment by Electro707** [comment]
Personally, what I have been doing is either going off existing models or make a brand new svg based off `dummy.svg`, then manually build out the drawing based off the KiCAD footprint (for origin points), then create an empty board with the footprint and generate that with `pcbdraw` and see how it comes out

**Comment by MatteoTondelli** [comment]
> Unfortunately I don't see an easy way of updating the script without a lot of extra effort.

Yeah, I also tried to figure out if a quick workaround would have been feasible, but it seems a lot of things had changed...

**Comment by yaqwsx** [comment]
Hi, sorry for a long delay. The script is indeed broken. I originally wanted to update it until the v1 release, however, there wasn't enough time and I needed to release v1 ASAP (in order to coordinate with other projects). The plan is to depreceate these script and put them inside PcbDraw – the target is v1.1, hopefully end of January 2023.

**Comment by n-i-x** [comment]
This is still broken. I went down the path of migrating to make it work until I hit `AttributeError: module 'pcbdraw' has no attribute 'process_board_substrate_layer'`

At this point, I gave up as I realized the entire API has changed.

**Comment by nopeppermint** [comment]
I have the same problem, would be nice if you could fix it

**Comment by MrRyzz** [comment]
Any news?

**Comment by guigur** [comment]
up

**Comment by yaqwsx** [comment]
c53546772f98176dab4d47454ad8c9db578cec76.This was resolved in https://github.com/yaqwsx/PcbDraw/commit/5c6e185107e7e07fc899827d9aa8bd3f194cce2d and
